language: node_js
node_js: "stable"
install:
  - npm install
script:
  - npm test
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - createuser emmabaye -s -U postgres
  - createdb database_test --username=emmabaye
after_success:
  - npm run coverage  
